name: roteiro1
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.2 <4.0.0"

dependencies:
  stroke_text: any
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: PixelifySans
      fonts:
        - asset: assets/fonts/PixelifySans-Regular.ttf
  assets:
    - assets/images/bart.jpg
    - assets/images/homer.jpg
    - assets/images/lisa.png
    - assets/images/marge.jpg
    - assets/images/meg.png
    - assets/images/simpsons.jpg
